### ISSUE TITLE
Blank Page due to conflict with other forms

### ISSUE THREAD

**Issue by anantajitjg** [imranhsayed/frontity-contact-form-7#29]
**Issue**

If I add a form in a page other than contact form 7 form then a blank page will be returned with an error:
TypeError: state.cf7.forms[id] is undefined
This issue only happens if the form contains any hidden input fields(most likely/definitely).

**Steps to replicate the issue**

Create any page in WordPress with forms generated by other plugins(e.g. Everest Forms) and add this page to menu in frontity.settings.js and access that page with 'frontity-contact-form-7' package added in the settings.

**Fix/Suggestion**

Be more specific with the hidden input fields selection test method in the cf7HiddenInputs processor.

**Screenshots**

![Screenshot 2020-06-14 at 12 08 55 AM](https://user-images.githubusercontent.com/22009263/84577349-1cbedb80-add9-11ea-93b5-e493fb4e4c46.png)
![Screenshot 2020-06-14 at 12 07 58 AM](https://user-images.githubusercontent.com/22009263/84577355-28aa9d80-add9-11ea-91d9-c4c9f01a9759.png)

**Comment by luisherranz** [comment]
Hey @anantajitjg, good catch 🙂

Could you please do a PR with your fix?
